FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

ENV WATCHPACK_POLLING=true
ENV CHOKIDAR_USEPOLLING=true
ENV HOSTNAME=0.0.0.0
ENV PORT=3000

EXPOSE ${PORT}

CMD ["sh", "-c", "npx next dev -H 0.0.0.0 -p ${PORT}"]